name: Build Android apk

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    - run: gradle setupTonalityDependencies
    - run: gradle build
    
    - uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: app/build/reports
    
    - uses: actions/upload-artifact@v3
      with:
        name: tonality
        path: app/build/outputs/apk/dev/debug/tonality-debug.apk
